spring.application.name=HR-mcp-client


spring.ai.openai.api-key=

spring.ai.openai.chat.temperature=0
spring.ai.openai.base-url=https://openrouter.ai/api/v1
spring.ai.openai.chat.model=openrouter/free
logging.level.org.springframework.ai.chat.client.advisor=DEBUG

server.port=8081
# MCP client properties
spring.ai.mcp.client.name=hrclient
spring.ai.mcp.client.version=1.0.0
spring.ai.mcp.client.type=SYNC
spring.ai.mcp.client.request-timeout=30s

#MCP server properties
spring.ai.mcp.client.streamable-http.connections.hr-leave-server.url=http://localhost:8080
spring.ai.mcp.client.streamable-http.connections.hr-leave-server.endpoint=/mcp